### ISSUE TITLE
Wrong decoding of "compression 3" image

### ISSUE THREAD

**Issue by massic80** [photopea/UTIF.js#77]
Hi, I am using UTIF on a project and just created an image with Irfanview.
[tif.zip](https://github.com/photopea/UTIF.js/files/3701783/tif.zip)
Looks like it uses _compression 3_, but it doesn't work on my application nor on Photopea.
Is it a bug or isn't it expected to work?

**Comment by photopea** [comment]
UTIF was not able to correctly detect between Fax Group 3 1-D and Fax Group 3 2-D compressoin. My "guessing method" worked almost always, and your image is exactly the one where it does not work.

Turns out there is a TIFF tag 292, which explicitly specifies, that the data is Fax Group 3 2-D (and 1-D should be used otherwise). So I fixed it :)

**Comment by massic80** [comment]
When do you think it will be deployed on npm?

**Comment by photopea** [comment]
I am sorry, I am not an NPM user and I maintain it only here on Github :/ Maybe @Scimonster  could upload it to npm?

Or you can just copy-paste the code from here into your project.

**Comment by massic80** [comment]
Ah, sorry, I wrote to you since I saw you also have an account there :)
I'd better wait for @Scimonster , since I want any of our machines aligned ;)
Thanks again!
