### ISSUE TITLE
Support for online URL's like s3 images. 

### ISSUE THREAD

**Issue by vishnup95** [photopea/UTIF.js#81]
Hey @photopea , 

Raising this issue as it has been haunting me for some time. The library is cool. I am able to view .tiff images in the browser when they are placed in my local directory. I have multiple files from an s3 bucket with a very weird URL. ( I will provide a URL if it's needed.) 

UTIF.replaceIMG() seems to only work with images within the local directory but when I try to load an image with URL. Nothing seems to load. 

`<img src="some_s3_bucket.url" ...../>`

Do you have any idea why this is the behavior?

**Comment by photopea** [comment]
Hi, in this case, the javascript on your site (UTIF.js) needs to access the binary file (its bytes), which comes from another domain.

I believe the problem is in CORS https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS . By default, websites can not read data from another domains, unless a specific header is included in a HTTP response.

**Comment by photopea** [comment]
I think it was solved by CORS.
